import os

NETWORKAPI_ENDPOINT = os.getenv('NETWORKAPI_ENDPOINT')
NETWORKAPI_USER = os.getenv('NETWORKAPI_USER')
NETWORKAPI_PASSWORD = os.getenv('NETWORKAPI_PASSWORD')
NETWORKAPI_RMQ_USER = os.getenv('NETWORKAPI_RMQ_USER')
NETWORKAPI_RMQ_PASSWORD = os.getenv('NETWORKAPI_RMQ_PASSWORD')
NETWORKAPI_RMQ_HOST = os.getenv('NETWORKAPI_RMQ_HOST')
NETWORKAPI_RMQ_PORT = int(os.getenv('NETWORKAPI_RMQ_PORT'))
NETWORKAPI_RMQ_VIRTUAL_HOST = os.getenv('NETWORKAPI_RMQ_VIRTUAL_HOST')
